apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kube-local-storgae
  local:
    path: /Users/varunrajput/mobilityware
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
